import { Geist, Geist_Mono, Inter, Roboto } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { ToastContainer } from "react-toastify";
import axios from "axios";
import Header from "@/components/header";
import AppBar from "@/components/appBar";
import DateContextProvider from "@/context/DateContext";

const inter = Inter({
  weight: ['400', '700'],
  subsets: ["latin"],
  display: 'swap'
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <AppRouterCacheProvider>
          <DateContextProvider>
            {children}
          </DateContextProvider>
        </AppRouterCacheProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
